@echo off
echo Setting up Google Cloud configuration...

echo.
echo Step 1: Setting account...
"C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud" config set account berkeley@blkoutuk.com
echo Press any key to continue...
pause > nul

echo.
echo Step 2: Setting project...
"C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud" config set project onboardblkoutnxt
echo Press any key to continue...
pause > nul

echo.
echo Step 3: Enabling Google Sheets API...
"C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud" services enable sheets.googleapis.com
echo Press any key to continue...
pause > nul

echo.
echo Step 4: Showing current configuration...
"C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud" config list
echo Press any key to continue...
pause > nul

echo.
echo Step 5: Creating service account...
"C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud" iam service-accounts create blkoutnxt-sheets --description="Service account for BLKOUTNXT Google Sheets integration" --display-name="BLKOUTNXT Sheets"
echo Press any key to continue...
pause > nul

echo.
echo Step 6: Creating service account key...
"C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud" iam service-accounts keys create key.json --iam-account=blkoutnxt-sheets@onboardblkoutnxt.iam.gserviceaccount.com
echo Press any key to continue...
pause > nul

echo.
echo Setup complete! Press any key to exit...
pause > nul 